### ISSUE TITLE
'remember me' broken?

### ISSUE THREAD

**Issue by Dutchy-** [Venefilyn/CodeIgniter-Ion-Auth-OTP#3]
Is it possible that you broke the 'remember me'-functionality of Ion Auth?

I'm looking at this:

https://github.com/SpyTec/CodeIgniter-Ion-Auth-OTP/blob/2-step-auth/controllers/auth.php#L78

Where the flash data key is 'remember_me', but at

https://github.com/SpyTec/CodeIgniter-Ion-Auth-OTP/blob/2-step-auth/controllers/auth.php#L128
https://github.com/SpyTec/CodeIgniter-Ion-Auth-OTP/blob/2-step-auth/controllers/auth.php#L177

The flashdata key is 'remember'.

**Comment by Venefilyn** [comment]
Should be fixed now. The form itself has nothing to do with flashdata but I did forget flashdata should've been remember_me instead of remember. Thanks!
