### ISSUE TITLE
What is this hidden field?

### ISSUE THREAD

**Issue by michaelsmoody** [Venefilyn/CodeIgniter-Ion-Auth-OTP#4]
@SpyTec I haven't yet dug into this in depth, but I was wondering what the hidden form field otp_login_key is? Would it be better to set this via session data (server side)?

**Comment by Venefilyn** [comment]
There could be name changes to better suit what the strings are, but it's a temporary hash that authenticates your first step when you're on validating the OTP.

The way this is setup is that if OTP is enabled in config and the user has it activated is that once your first step is authenticated, username and password it'll generate a hash, set it as flashdata and redirect you to a second login-page that contains OTP-field and the otp_login_key to represent your first validation
